name: claimcentral
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.6
  file_picker: ^5.2.6
  path: ^1.8.0
  http: ^1.2.1
  flutter_secure_storage: ^8.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/app-logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#044280"
  adaptive_icon_foreground: "assets/app-logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/app-logo.png
    - assets/profile.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
